
version: '3.1'

services:

  mysql-8-0-36:
    image: mysql:8.0.36
    container_name: mysql-8-0-36
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
